# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 00:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('aceptado', models.NullBooleanField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpros.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Obligatorio. Maximo 20 caracteres.', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Un maximo de 200 caracteres.', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el proyecto se encuentra abierto o cerrado.')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(choices=[(b'JP', b'Jefe de Proyecto'), (b'AN', b'Analista'), (b'DI', b'Dise\xc3\xb1ador'), (b'AP', b'Analista Programador'), (b'RE', b'Responsable'), (b'PR', b'Programador'), (b'QA', b'Probador')], default=b'JP', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dni', models.CharField(blank=True, help_text='Required. 9 characters. Format: 71254631D.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(b'^\\d{8}[A-Z]{1}$', 'Introduce un DNI valido. Formato: 71254631D.')], verbose_name=b'DNI')),
                ('categoria', models.CharField(choices=[(b'J', b'Jefe'), (b'D', b'Desarrollador')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gtpros.Proyecto')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Resumenes',
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtpros.Proyecto'),
        ),
        migrations.AddField(
            model_name='rol',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpros.Trabajador'),
        ),
        migrations.AddField(
            model_name='hito',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpros.Proyecto'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpros.Proyecto'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpros.Rol'),
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together=set([('trabajador', 'proyecto')]),
        ),
    ]
