# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('JF', 'Jefe'), ('AN', 'Analista'), ('DI', 'Diseñador'), ('AP', 'Analista Programador'), ('RE', 'Responsable'), ('PR', 'Programador'), ('QA', 'Probador')], max_length=1),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
