# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumen',
            options={'verbose_name_plural': 'Res�menes'},
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='id',
        ),
        migrations.AlterField(
            model_name='resumen',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gtpros.Proyecto'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtpros.Proyecto'),
        ),
    ]
