# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[(b'N', b'Inicial'), (b'A', b'Asignaci\xc3\xb3n'), (b'P', b'Preparado'), (b'I', b'Iniciado'), (b'F', b'Finalizado')], default=b'N', max_length=1),
        ),
    ]
