# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
