# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0002_auto_20160112_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
