# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0002_auto_20160108_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gtpros.Proyecto'),
        ),
    ]
