# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtpros', '0003_auto_20151231_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
