# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0004_auto_20160127_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='id_evento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo_rol',
            field=models.CharField(choices=[(b'AN', b'Analista'), (b'DI', b'Dise\xc3\xb1ador'), (b'AP', b'Analista Programador'), (b'RP', b'Responsable'), (b'PG', b'Programador'), (b'QA', b'Probador')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rol',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtpros.Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together=set([('id', 'proyecto')]),
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together=set([]),
        ),
    ]
