# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0004_trabajador_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='dni',
            new_name='DNI',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='user',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
