# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0006_auto_20160128_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_rol',
            field=models.CharField(blank=True, choices=[(b'AN', b'Analista'), (b'DI', b'Dise\xc3\xb1ador'), (b'AP', b'Analista Programador'), (b'RP', b'Responsable'), (b'PG', b'Programador'), (b'QA', b'Probador')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[(b'N', b'Inicial'), (b'C', b'Calendarizaci\xc3\xb3n'), (b'A', b'Asignaci\xc3\xb3n'), (b'P', b'Preparado'), (b'I', b'Iniciado'), (b'F', b'Finalizado')], default=b'N', max_length=1),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gtpros.Trabajador'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together=set([('trabajador', 'evento')]),
        ),
    ]
