# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0010_auto_20160205_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('siglas', models.CharField(max_length=2)),
                ('min_cat', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtpros.TipoRol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpros.TipoRol'),
        ),
    ]
