# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0011_auto_20160205_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiporol',
            options={'verbose_name': 'Tipo de Rol', 'verbose_name_plural': 'Tipos de Rol'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='es_jefe',
            field=models.BooleanField(default=True, verbose_name=b'\xc2\xbfJefe del Proyecto?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion',
            field=models.IntegerField(default=0, verbose_name=b'Duraci\xc3\xb3n en horas/hombre'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(null=True, verbose_name=b'Fecha final'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name=b'Fecha inicial'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtpros.TipoRol', verbose_name=b'Tipo de rol requerido'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name=b'Fecha final'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name=b'Fecha inicial'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(help_text='Obligatorio. Maximo 30 caracteres.', max_length=30),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpros.TipoRol', verbose_name=b'Tipo de Rol'),
        ),
        migrations.AlterField(
            model_name='tiporol',
            name='min_cat',
            field=models.IntegerField(verbose_name=b'Categor\xc3\xada m\xc3\xadnima'),
        ),
        migrations.AlterField(
            model_name='tiporol',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tiporol',
            name='siglas',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
