# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0012_auto_20160205_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gtpros.Rol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informe',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='jueves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='lunes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='martes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='miercoles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='viernes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
