# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0013_auto_20160205_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='evento',
        ),
    ]
