# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0014_remove_informe_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
