# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0016_auto_20160209_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='miercoles',
            new_name='tarea6',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='viernes',
        ),
        migrations.AddField(
            model_name='informe',
            name='tarea1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='tarea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='tarea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='tarea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='tarea5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
