# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0017_auto_20160209_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='tarea1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tarea2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tarea3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tarea4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tarea5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tarea6',
            field=models.IntegerField(default=0),
        ),
    ]
