# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpros', '0018_auto_20160210_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='informes_generados',
            field=models.BooleanField(default=False),
        ),
    ]
